"""initial relational schema

Revision ID: d37bd727689e
Revises: 
Create Date: 2026-07-27 12:39:24.917282
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd37bd727689e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_provider', sa.String(length=50), nullable=True),
    sa.Column('external_player_id', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('matching_status', sa.String(length=30), nullable=False),
    sa.Column('manual_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("matching_status IN ('certain_external_id','manual_confirmed','new_player','possible_match','conflict','homonym')", name='ck_players_matching_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_provider', 'external_player_id', name='uq_players_provider_external_id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('ranking_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=1), nullable=True),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IS NULL OR role IN ('P','D','C','A')", name='ck_ranking_configs_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=9), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('end_year = start_year + 1', name='ck_seasons_consecutive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('player_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('first_seen_season_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['last_seen_season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'source_provider', 'source_name', name='uq_player_aliases_player_provider_name')
    )
    with op.batch_alter_table('player_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_aliases_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('classic_role', sa.String(length=1), nullable=False),
    sa.Column('mantra_roles', sa.String(length=100), nullable=False),
    sa.Column('rated_appearances', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('fantasy_average', sa.Float(), nullable=True),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('penalties_saved', sa.Integer(), nullable=False),
    sa.Column('penalties_taken', sa.Integer(), nullable=False),
    sa.Column('penalties_scored', sa.Integer(), nullable=False),
    sa.Column('penalties_missed', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=False),
    sa.Column('has_valid_rating', sa.Boolean(), nullable=False),
    sa.Column('source_record_count', sa.Integer(), nullable=False),
    sa.Column('quality_status', sa.String(length=20), nullable=False),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.CheckConstraint("classic_role IN ('P','D','C','A')", name='ck_player_season_stats_classic_role'),
    sa.CheckConstraint("quality_status IN ('valid','warning','error')", name='ck_player_season_stats_quality_status'),
    sa.CheckConstraint('(rated_appearances = 0 AND average_rating IS NULL AND fantasy_average IS NULL AND has_valid_rating = 0) OR (rated_appearances > 0 AND average_rating IS NOT NULL AND fantasy_average IS NOT NULL AND has_valid_rating = 1)', name='ck_stats_rating_presence'),
    sa.CheckConstraint('average_rating IS NULL OR average_rating >= 0', name='ck_stats_average_nonnegative'),
    sa.CheckConstraint('fantasy_average IS NULL OR fantasy_average >= 0', name='ck_stats_fantasy_nonnegative'),
    sa.CheckConstraint('goals_scored >= 0 AND goals_conceded >= 0 AND penalties_saved >= 0 AND penalties_taken >= 0 AND penalties_scored >= 0 AND penalties_missed >= 0 AND assists >= 0 AND yellow_cards >= 0 AND red_cards >= 0 AND own_goals >= 0', name='ck_stats_additive_nonnegative'),
    sa.CheckConstraint('penalties_taken = penalties_scored + penalties_missed', name='ck_stats_penalty_identity'),
    sa.CheckConstraint('rated_appearances >= 0', name='ck_stats_rated_nonnegative'),
    sa.CheckConstraint('source_record_count >= 1', name='ck_stats_source_record_count'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', name='uq_player_season_stats_player_season')
    )
    op.create_table('source_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('import_type', sa.String(length=40), nullable=False),
    sa.Column('source_filename', sa.String(length=500), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name='ck_source_imports_status'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_type', 'source_sha256', name='uq_source_imports_type_sha256')
    )
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('external_player_id', sa.String(length=100), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("validation_status IN ('pending','valid','warning','error','excluded')", name='ck_source_records_validation_status'),
    sa.ForeignKeyConstraint(['import_id'], ['source_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'record_hash', name='uq_source_records_import_hash'),
    sa.UniqueConstraint('import_id', 'sheet_name', 'source_row_number', name='uq_source_records_import_sheet_row')
    )
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_records_external_player_id'), ['external_player_id'], unique=False)

    op.create_table('current_season_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('source_record_id', sa.Integer(), nullable=False),
    sa.Column('external_player_id', sa.String(length=100), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('official_classic_role', sa.String(length=1), nullable=False),
    sa.Column('official_mantra_roles', sa.String(length=100), nullable=True),
    sa.Column('official_team_id', sa.Integer(), nullable=True),
    sa.Column('quotation', sa.Float(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mapping_status', sa.String(length=30), nullable=False),
    sa.CheckConstraint("mapping_status IN ('pending','certain_external_id','manual_confirmed','new_player','possible_match','conflict','homonym','excluded')", name='ck_current_list_mapping_status'),
    sa.ForeignKeyConstraint(['official_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'source_record_id', name='uq_current_list_season_record')
    )
    op.create_table('player_mapping_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=False),
    sa.Column('suggested_player_id', sa.Integer(), nullable=True),
    sa.Column('candidate_player_id', sa.Integer(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolved_player_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','resolved','excluded')", name='ck_player_mapping_reviews_status'),
    sa.CheckConstraint('similarity_score IS NULL OR (similarity_score >= 0 AND similarity_score <= 100)', name='ck_player_mapping_reviews_similarity'),
    sa.ForeignKeyConstraint(['candidate_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['resolved_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_team_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_season_stats_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('association_type', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("association_type IN ('observed','final','partial','unknown')", name='ck_player_team_seasons_association_type'),
    sa.ForeignKeyConstraint(['player_season_stats_id'], ['player_season_stats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_season_stats_id', 'team_id', 'association_type', name='uq_player_team_season_association')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_team_seasons')
    op.drop_table('player_mapping_reviews')
    op.drop_table('current_season_list')
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_records_external_player_id'))

    op.drop_table('source_records')
    op.drop_table('source_imports')
    op.drop_table('player_season_stats')
    with op.batch_alter_table('player_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_aliases_normalized_name'))

    op.drop_table('player_aliases')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_table('ranking_configs')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_normalized_name'))

    op.drop_table('players')
    # ### end Alembic commands ###

